import z from "zod";

import {
  EXCLUDED_CASE_INSENSITIVE_NVARCHAR_SCHEMA,
  NO_LEADING_AND_TRAILING_WHITESPACE_SCHEMA,
} from "../constants/CheckConstraintConstants";
import { MSSQL_BIT_SCHEMA } from "../constants/TSQLDataTypeConstants";
import { zodExclude } from "../utils/zodUtils";

export const EndUserRoleSchema = z.object({
  CreateAsset: MSSQL_BIT_SCHEMA,
  CreateAssetFix: MSSQL_BIT_SCHEMA,
  CreateAssetIssue: MSSQL_BIT_SCHEMA,
  CreateAssetTransfer: MSSQL_BIT_SCHEMA,
  CreateBuilding: MSSQL_BIT_SCHEMA,
  CreateCategory: MSSQL_BIT_SCHEMA,
  CreateCompany: MSSQL_BIT_SCHEMA,
  CreateDepartment: MSSQL_BIT_SCHEMA,
  CreateEmployee: MSSQL_BIT_SCHEMA,
  CreateEndUser: MSSQL_BIT_SCHEMA,
  CreateEndUserRole: MSSQL_BIT_SCHEMA,
  CreateLocation: MSSQL_BIT_SCHEMA,
  CreateManufacturer: MSSQL_BIT_SCHEMA,
  CreateProduct: MSSQL_BIT_SCHEMA,
  CreateProductSet: MSSQL_BIT_SCHEMA,
  CreateRole: MSSQL_BIT_SCHEMA,
  CreateVendor: MSSQL_BIT_SCHEMA,
  DeleteAsset: MSSQL_BIT_SCHEMA,
  DeleteAssetFix: MSSQL_BIT_SCHEMA,
  DeleteAssetIssue: MSSQL_BIT_SCHEMA,
  DeleteAssetTransfer: MSSQL_BIT_SCHEMA,
  DeleteBuilding: MSSQL_BIT_SCHEMA,
  DeleteCategory: MSSQL_BIT_SCHEMA,
  DeleteCompany: MSSQL_BIT_SCHEMA,
  DeleteDepartment: MSSQL_BIT_SCHEMA,
  DeleteEmployee: MSSQL_BIT_SCHEMA,
  DeleteEndUser: MSSQL_BIT_SCHEMA,
  DeleteEndUserRole: MSSQL_BIT_SCHEMA,
  DeleteLocation: MSSQL_BIT_SCHEMA,
  DeleteLog: MSSQL_BIT_SCHEMA,
  DeleteManufacturer: MSSQL_BIT_SCHEMA,
  DeleteProduct: MSSQL_BIT_SCHEMA,
  DeleteProductSet: MSSQL_BIT_SCHEMA,
  DeleteRole: MSSQL_BIT_SCHEMA,
  DeleteVendor: MSSQL_BIT_SCHEMA,
  EndUserRoleCreationDate: z.date(),
  EndUserRoleID: z.uuid({ version: "v4" }),
  EndUserRoleName: zodExclude(
    NO_LEADING_AND_TRAILING_WHITESPACE_SCHEMA.min(1).max(850),
    EXCLUDED_CASE_INSENSITIVE_NVARCHAR_SCHEMA,
  ),
  ReadAsset: MSSQL_BIT_SCHEMA,
  ReadAssetFix: MSSQL_BIT_SCHEMA,
  ReadAssetIssue: MSSQL_BIT_SCHEMA,
  ReadAssetTransfer: MSSQL_BIT_SCHEMA,
  ReadBuilding: MSSQL_BIT_SCHEMA,
  ReadCategory: MSSQL_BIT_SCHEMA,
  ReadCompany: MSSQL_BIT_SCHEMA,
  ReadDepartment: MSSQL_BIT_SCHEMA,
  ReadEmployee: MSSQL_BIT_SCHEMA,
  ReadEndUser: MSSQL_BIT_SCHEMA,
  ReadEndUserRole: MSSQL_BIT_SCHEMA,
  ReadLocation: MSSQL_BIT_SCHEMA,
  ReadLog: MSSQL_BIT_SCHEMA,
  ReadManufacturer: MSSQL_BIT_SCHEMA,
  ReadProduct: MSSQL_BIT_SCHEMA,
  ReadProductSet: MSSQL_BIT_SCHEMA,
  ReadRole: MSSQL_BIT_SCHEMA,
  ReadVendor: MSSQL_BIT_SCHEMA,
  UpdateAsset: MSSQL_BIT_SCHEMA,
  UpdateAssetFix: MSSQL_BIT_SCHEMA,
  UpdateAssetIssue: MSSQL_BIT_SCHEMA,
  UpdateAssetTransfer: MSSQL_BIT_SCHEMA,
  UpdateBuilding: MSSQL_BIT_SCHEMA,
  UpdateCategory: MSSQL_BIT_SCHEMA,
  UpdateCompany: MSSQL_BIT_SCHEMA,
  UpdateDepartment: MSSQL_BIT_SCHEMA,
  UpdateEmployee: MSSQL_BIT_SCHEMA,
  UpdateEndUser: MSSQL_BIT_SCHEMA,
  UpdateEndUserRole: MSSQL_BIT_SCHEMA,
  UpdateLocation: MSSQL_BIT_SCHEMA,
  UpdateManufacturer: MSSQL_BIT_SCHEMA,
  UpdateProduct: MSSQL_BIT_SCHEMA,
  UpdateProductSet: MSSQL_BIT_SCHEMA,
  UpdateRole: MSSQL_BIT_SCHEMA,
  UpdateVendor: MSSQL_BIT_SCHEMA,
});

export type EndUserRole = z.infer<typeof EndUserRoleSchema>;
