import z from "zod";

import {
  EXCLUDED_CASE_INSENSITIVE_NVARCHAR_SCHEMA,
  EXCLUDED_DATETIMEOFFSET_SCHEMA,
  EXCLUDED_UNIQUEIDENTIFIER_SCHEMA,
  NO_LEADING_AND_TRAILING_WHITESPACE_SCHEMA,
} from "../constants/CheckConstraintConstants";
import {
  TSQL_BIT_SCHEMA,
  TSQL_DATETIMEOFFSET_SCHEMA,
} from "../constants/TSQLDataTypeConstants";
import { zodExclude } from "../utils/zodUtils";

export const EndUserRoleSchema = z.object({
  CreateAsset: TSQL_BIT_SCHEMA,
  CreateAssetFix: TSQL_BIT_SCHEMA,
  CreateAssetIssue: TSQL_BIT_SCHEMA,
  CreateAssetTransfer: TSQL_BIT_SCHEMA,
  CreateBuilding: TSQL_BIT_SCHEMA,
  CreateCategory: TSQL_BIT_SCHEMA,
  CreateCompany: TSQL_BIT_SCHEMA,
  CreateDepartment: TSQL_BIT_SCHEMA,
  CreateEmployee: TSQL_BIT_SCHEMA,
  CreateEndUser: TSQL_BIT_SCHEMA,
  CreateEndUserRole: TSQL_BIT_SCHEMA,
  CreateLocation: TSQL_BIT_SCHEMA,
  CreateManufacturer: TSQL_BIT_SCHEMA,
  CreateProduct: TSQL_BIT_SCHEMA,
  CreateProductSet: TSQL_BIT_SCHEMA,
  CreateRole: TSQL_BIT_SCHEMA,
  CreateVendor: TSQL_BIT_SCHEMA,
  DeleteAsset: TSQL_BIT_SCHEMA,
  DeleteAssetFix: TSQL_BIT_SCHEMA,
  DeleteAssetIssue: TSQL_BIT_SCHEMA,
  DeleteAssetTransfer: TSQL_BIT_SCHEMA,
  DeleteBuilding: TSQL_BIT_SCHEMA,
  DeleteCategory: TSQL_BIT_SCHEMA,
  DeleteCompany: TSQL_BIT_SCHEMA,
  DeleteDepartment: TSQL_BIT_SCHEMA,
  DeleteEmployee: TSQL_BIT_SCHEMA,
  DeleteEndUser: TSQL_BIT_SCHEMA,
  DeleteEndUserRole: TSQL_BIT_SCHEMA,
  DeleteLocation: TSQL_BIT_SCHEMA,
  DeleteLog: TSQL_BIT_SCHEMA,
  DeleteManufacturer: TSQL_BIT_SCHEMA,
  DeleteProduct: TSQL_BIT_SCHEMA,
  DeleteProductSet: TSQL_BIT_SCHEMA,
  DeleteRole: TSQL_BIT_SCHEMA,
  DeleteVendor: TSQL_BIT_SCHEMA,
  EndUserRoleCreationDate: zodExclude(
    TSQL_DATETIMEOFFSET_SCHEMA,
    EXCLUDED_DATETIMEOFFSET_SCHEMA,
  ),
  EndUserRoleID: zodExclude(
    z.uuid({ version: "v4" }),
    EXCLUDED_UNIQUEIDENTIFIER_SCHEMA,
  ),
  EndUserRoleName: zodExclude(
    NO_LEADING_AND_TRAILING_WHITESPACE_SCHEMA.min(1).max(850),
    EXCLUDED_CASE_INSENSITIVE_NVARCHAR_SCHEMA,
  ),
  ReadAsset: TSQL_BIT_SCHEMA,
  ReadAssetFix: TSQL_BIT_SCHEMA,
  ReadAssetIssue: TSQL_BIT_SCHEMA,
  ReadAssetTransfer: TSQL_BIT_SCHEMA,
  ReadBuilding: TSQL_BIT_SCHEMA,
  ReadCategory: TSQL_BIT_SCHEMA,
  ReadCompany: TSQL_BIT_SCHEMA,
  ReadDepartment: TSQL_BIT_SCHEMA,
  ReadEmployee: TSQL_BIT_SCHEMA,
  ReadEndUser: TSQL_BIT_SCHEMA,
  ReadEndUserRole: TSQL_BIT_SCHEMA,
  ReadLocation: TSQL_BIT_SCHEMA,
  ReadLog: TSQL_BIT_SCHEMA,
  ReadManufacturer: TSQL_BIT_SCHEMA,
  ReadProduct: TSQL_BIT_SCHEMA,
  ReadProductSet: TSQL_BIT_SCHEMA,
  ReadRole: TSQL_BIT_SCHEMA,
  ReadVendor: TSQL_BIT_SCHEMA,
  UpdateAsset: TSQL_BIT_SCHEMA,
  UpdateAssetFix: TSQL_BIT_SCHEMA,
  UpdateAssetIssue: TSQL_BIT_SCHEMA,
  UpdateAssetTransfer: TSQL_BIT_SCHEMA,
  UpdateBuilding: TSQL_BIT_SCHEMA,
  UpdateCategory: TSQL_BIT_SCHEMA,
  UpdateCompany: TSQL_BIT_SCHEMA,
  UpdateDepartment: TSQL_BIT_SCHEMA,
  UpdateEmployee: TSQL_BIT_SCHEMA,
  UpdateEndUser: TSQL_BIT_SCHEMA,
  UpdateEndUserRole: TSQL_BIT_SCHEMA,
  UpdateLocation: TSQL_BIT_SCHEMA,
  UpdateManufacturer: TSQL_BIT_SCHEMA,
  UpdateProduct: TSQL_BIT_SCHEMA,
  UpdateProductSet: TSQL_BIT_SCHEMA,
  UpdateRole: TSQL_BIT_SCHEMA,
  UpdateVendor: TSQL_BIT_SCHEMA,
});

export type EndUserRole = z.infer<typeof EndUserRoleSchema>;
